name: Node Matrix Example

on:
  push:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - version: ubuntu-latest
            scope: 18
          - version: windows-latest
            scope: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: print version
        run: |
          echo "version: ${{ matrix.version }}"
          echo "scope: ${{ matrix.scope }}"
        
