name: Node Matrix Example

on:
  push:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [16, 18, 20]
        scope: ["x", "y", "z", "w"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: print version
        run: |
          echo "version: ${{ matrix.version }}"
          echo "scope: ${{ matrix.scope }}"
        
