name: Node Matrix Example

on:
  push:
  workflow_dispatch: 

jobs:

  prepare:
    runs-on: ubuntu-latest
    outputs:
      jobs: ${{ steps.generate.outputs.jobs }}

    steps:
      - name: Generate matrix
        id: generate
        run: |
          echo "jobs=[1, 2, 3, 4, 5]" >> $GITHUB_OUTPUT

  run:
    needs: prepare

    strategy:
      matrix: 
        color: ${{ fromJson(needs.prepare.outputs.jobs) }}

    runs-on: ubuntu-latest

    steps:
      - name: Print job number
        run: echo "Running job ${{ matrix.color }}"
